name: "Auto-publish NPM Package"

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: "Setup, and publish"
    runs-on: ubuntu-latest
    env:
      # NOTE: Change this to the directory where your package lives
      PACKAGE_DIR: "packages/change-this-adapter"

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - name: "Set up Node"
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "lts/*"
          check-latest: true

      - name: "Dependencies and tests"
        run: |
          npm ci
          npm run build --workspace ${{ env.PACKAGE_DIR }}

          # Remove test files/folders so they aren't published to NPM
          find ./${{ env.PACKAGE_DIR }}/dist -name "*.test.*" -delete
          find ./${{ env.PACKAGE_DIR }}/dist -name "test" -type d  | xargs rm -rf;

      - name: "Publish to NPM"
        uses: JS-DevTools/npm-publish@v3
        with:
          package: "./packages/change-this-adapter/package.json"
          token: ${{ secrets.NPM_TOKEN }}
